### ISSUE TITLE
route /login on front is not working 

### ISSUE THREAD

**Issue by tpayet** [tpayet/Hypertube#43]
When I go on `https://hypertube.tpayet.com/` the url is rewrited to `https://hypertube.tpayet.com/login`

But if I refresh the page, I have a 404 error because the router can not route to /login

**Comment by ssumodhe** [comment]
I see the problem, but it doesnt happen when I use localhost .. And the 404 page displayed is not the front's 404 page . . Seems like it's comming from the server . .
