### ISSUE TITLE
Front: mixed source loading blocked

### ISSUE THREAD

**Issue by ndudnicz** [tpayet/Hypertube#44]
`Blocked loading mixed active content “http://vjs.zencdn.net/6.6.3/video-js.css”`
`Blocked loading mixed active content “http://vjs.zencdn.net/6.6.3/video.js”`

**Comment by ssumodhe** [comment]
done ! ;) 
Changed http:// into http**s**://
branch front_saf commit 750ab5a759e7e898aab5ef38fd3034e6433242d8
