### ISSUE TITLE
Front: some input fields are missing, none of those updates work, ...and stuff

### ISSUE THREAD

**Issue by ndudnicz** [tpayet/Hypertube#48]
#### Missing:
* New email input
* New password confirmation input

#### CSS:
* Picture dropzone: we might reduce the 2 elements' z-index (ie: canva and div), so it won't go over the navbar when you scroll down.

#### HTML:
* Password inputs' type must be password

#### General:
* Is it good that the users can change their username ?
* Updates don't update

#### CSS:
* Picture dropzone: we might reduce the 2 elements' z-index (ie: canva and div), so it won't go over the navbar when you scroll down.

**Comment by ssumodhe** [comment]
CSS - Picture dropzone and Navbar : **fixed** branch front_saf commit c0b5c3c9aac68e20338654297c190c550e8e951f

**Comment by ssumodhe** [comment]
Profile page (/user/:username) **in progress** -> Will come back to you when finished ! ;)
