### ISSUE TITLE
Back api: I can create accounts with yolo characters, error 422

### ISSUE THREAD

**Issue by ndudnicz** [tpayet/Hypertube#52]
#### On signup process:
* I can create an account with login: "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==" or "<script>alert(1)</script>"
* Error 422 when creating an account with a taken or invalid email
* Error 422 when trying to create an account with an invalid password

**Comment by tpayet** [comment]
2 & 3 are normal behaviors, there is also a error message

I will investigate for the first point

**Comment by ndudnicz** [comment]
You have to delete the front validation (regex pattern) to do the 1st point.
